### ISSUE TITLE
Code blocks not showing up under add-ons navbar due to chrome extensions/settings

### ISSUE THREAD

**Issue by matthew-ardi** [alexwforsythe/code-blocks#87] opened 2018-07-14 21:06 UTC
It's been a pattern to me that I had to reset my chrome settings and I think the high number of extensions that I used on my chrome caused it.

**Comment by alexwforsythe** [comment] 2020-09-09 01:00
I'm going to close this issue because I haven't been able to successfully reproduce it. If you find a particular extension that causes this or have some other way to reproduce the issue, feel free to reopen and post your findings. Thanks!

**Closed by alexwforsythe** 2020-09-09 01:00 UTC
