### ISSUE TITLE
ScriptError

### ISSUE THREAD

**Issue by dmnkkrst** [alexwforsythe/code-blocks#82] opened 2018-06-21 13:20 UTC
Since yesterday I receive this error message as soon as I try to execute code blocks.

> ScriptError: We're sorry, a server error occurred. Please wait a bit and try again.

**Comment by alexwforsythe** [comment] 2018-08-01 00:28
That seems like it could be a transient error with Google Apps Script. Can you still reproduce the error?

**Comment by alexwforsythe** [comment] 2018-10-26 06:37
Closing this out because it's been a couple months with no update. Feel free to reopen if you see the issue again.

**Closed by alexwforsythe** 2018-10-26 06:37 UTC

**Comment by zeilerphone** [comment] 2019-01-19 23:50
I got this issue, no idea why. Tried on different computers also.

**Comment by filimongeorge** [comment] 2019-02-04 19:56
I also got this issue, happening for a couple of days now. Worked when I first used the Add-On, but the next day I started getting the issue when trying to format the code.

@alexwforsythe

**Comment by GabrieleCalarota** [comment] 2021-05-19 09:40
Reopening cause I'm seeing the error now (worked for the first half of the day).

`ScriptError: We're sorry, a server error occurred. Please wait a bit and try again.`

![image](https://user-images.githubusercontent.com/20482413/118791426-fcc05380-b896-11eb-9c6f-ace5da521425.png)
