### ISSUE TITLE
"Start" menu doesn't appear

### ISSUE THREAD

**Issue by oshev** [alexwforsythe/code-blocks#70] opened 2018-04-26 08:30 UTC
I've added CodeBlocks to a document but when I go to Add-ons -> Code blocks, I only see "Help" menu. There is no "Start" there.

**Comment by alexwforsythe** [comment] 2018-05-12 00:59
Closing this as a duplicate of #66. Feel free to reopen it if you are still seeing the issue.

**Closed by alexwforsythe** 2018-05-12 00:59 UTC
