### ISSUE TITLE
Not showing as add-on

### ISSUE THREAD

**Issue by lwallmba** [alexwforsythe/code-blocks#80] opened 2018-06-19 21:57 UTC
I installed the add-on but there is nothing to click in the Add-Ons menu.

**Comment by alexwforsythe** [comment] 2018-06-19 22:54
Hi @lwallmba. Can you try refreshing your document a few times to see if it starts working? Also, can you check if the add-on works in a new document? Some users have reported that the add-on doesn't show up in certain files for some reason.

**Comment by mardi08** [comment] 2018-06-29 15:38
try to reset your browser settings

if you are using chrome, this might work.

especially if you have many chrome extensions installed on your browser.

**Comment by alexwforsythe** [comment] 2018-08-01 00:34
Closing as a duplicate of #77

**Closed by alexwforsythe** 2018-08-01 00:34 UTC
