### ISSUE TITLE
Couldn't get theme

### ISSUE THREAD

**Issue by ShocKwav3** [alexwforsythe/code-blocks#20] opened 2017-04-17 17:50 UTC
It was working few weeks back. now when i try to preview or highlight it it says "couldn't get theme"

**Comment by angantyr** [comment] 2017-04-17 17:51
same here. +1

**Comment by alexwforsythe** [comment] 2017-04-17 18:46
That would indicate that the add-on is having trouble fetching the themes from the CDN or GH. I tried to reproduce the issue, but it seems to be working right now.

Can you try one more time? If you still encounter the error, please provide your language and theme selection. Thanks.

**Comment by ShocKwav3** [comment] 2017-04-17 18:48
it works now!

**Comment by alexwforsythe** [comment] 2017-04-17 19:15
Great! I'll leave this open to remind me to go back and try to reproduce the issue.

I assume there was an outage on cdnjs which caused the theme fetch to fail. The fallback logic should have tried to fetch them from GH, but it must not have worked.

**Comment by angantyr** [comment] 2017-04-19 12:07
thanks. works for me too. you can probably close it.

**Closed** 2017-05-07 13:22 UTC

**Comment by dfrechette** [comment] 2018-02-08 01:17
Hello, I'm having a similar issue with the `docco` theme. I have tried reload the document, opening the document in a new browser tab, I get the same error. When I change themes, e.g. `default`, it works.

<img width="302" alt="screen shot 2018-02-07 at 20 12 18" src="https://user-images.githubusercontent.com/14079/35950220-7392cc26-0c43-11e8-97bd-f87fcfdaa4ba.png">

**Comment by madooei** [comment] 2018-04-03 01:53
I have this problem for the "grayscale" theme. It has stopped working since last week and I've been waiting hopeful that the issue might resolve but it didn't.

**Comment by madooei** [comment] 2018-04-05 02:14
I removed the add-on and added it again and then problem has resolved. Thanks for your help.

**Comment by jalmansa88** [comment] 2018-07-02 20:03
Getting "Couldn't get theme" trying to format AndroidStudio style.

**Comment by ccbrucer** [comment] 2018-09-04 18:49
I have this problem "Couldn't get theme" for "Swift, vs2015". It worked days ago.
