### ISSUE TITLE
can't use tab in the formatted table

### ISSUE THREAD

**Issue by 2012215434** [alexwforsythe/code-blocks#25] opened 2017-07-26 07:08 UTC

**Comment by alexwforsythe** [comment] 2017-08-16 20:24
This is actually a feature of Google Docs and not a bug with Code Blocks. The purpose of this add-on is to add syntax highlighting to Docs, so adding code editing features would be out of scope.

If you're just trying to indent lines in your table, you can use the **Increase indent** button in the toolbar (<kbd>Command</kbd>+<kbd>]</kbd> on OS X or <kbd>Control</kbd>+<kbd>]</kbd> on Windows). Otherwise, the best workaround is to copy/paste a tab from somewhere else in your document.

**Closed by alexwforsythe** 2017-08-16 20:24 UTC
Labels: wontfix
