### ISSUE TITLE
There is an script authenticate error when start code blocks

### ISSUE THREAD

**Issue by dbthinh** [alexwforsythe/code-blocks#88] opened 2018-07-16 04:21 UTC
when i started code blocks, under the Theme selection box there is an error message said that "ScriptError: Authorization is required to perform that action.". I tried to reinstall the plugin again, allow all the authorization required but it didn't work.

**Comment by adam-hanna** [comment] 2018-07-31 18:54
Had the same issue, [this comment from another issue fixed it for me](https://github.com/alexwforsythe/code-blocks/issues/53#issuecomment-362250341).

Essentially, log out of all but one of your google accounts. [It's a known bug on google's end](https://issuetracker.google.com/issues/69270374).

**Comment by alexwforsythe** [comment] 2018-08-01 00:18
Thanks @adam-hanna. Closing as a duplicate of #53.

**Closed by alexwforsythe** 2018-08-01 00:18 UTC
