### ISSUE TITLE
Slides

### ISSUE THREAD

**Issue by shermozle** [alexwforsythe/code-blocks#85] opened 2018-06-26 03:41 UTC
I love your tool. It does exactly what it says on the tin!

Now what I'd really love is a version that does exactly the same in Google Slides. I'm often presenting snippets of code and they look terrible.

**Comment by alexwforsythe** [comment] 2018-10-26 06:41
Hi @shermozle. Glad to hear your enjoying Code Blocks!

I'm closing this as a duplicate of #73. Updates will be posted on that issue. Thanks!

**Closed by alexwforsythe** 2018-10-26 06:41 UTC
